version: "3.9"
services:
    wordpress:
        container_name: wordpress
        image: wordpress:latest
        ports:
            - 8080:80
        restart: always
        depends_on:
            - mysql
        environment:
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_PASSWORD=wordpress
            - WORDPRESS_DB_NAME=wordpress
        volumes:
            - /home/ubuntu/wp-project/wpmedia:/var/www/html/wp-content
        links:
            - mysql
    mysql:
        container_name: mysql
        image: mysql:8.0.19
        ports:
            - 3306:3306
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=wordpress
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress
        volumes:
            - /database/mysql:/var/lib/mysql
volumes:
    mysql_data:
    wordpress_data: